# hugo.toml

baseURL = "https://martinoall.github.io/MartinoA_portfolio/"
languageCode = "en-us"
title = "My Photography Portfolio"
theme = "beautifulhugo"
publishDir = "docs"
# generate links relative to that baseURL, so CSS/JS/images resolve correctly
relativeURLs = true
canonifyURLs = false

[pagination]
  pagerSize = 6
