# hugo.toml

baseURL = "https://martinoall.github.io/MartinoA_portfolio/"
languageCode = "en-us"
title = "My Photography Portfolio"
theme = "beautifulhugo"
publishDir = "docs"
# generate links relative to that baseURL, so CSS/JS/images resolve correctly
relativeURLs = false
canonifyURLs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 6
  



  [menu]

  [[menu.main]]
    name = "Work"
    url  = "/work/"
    weight = 10

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 30